# Generated by Django 5.1.3 on 2024-11-17 20:36

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('german', models.CharField(max_length=100, unique=True)),
                ('english', models.CharField(max_length=100)),
                ('french', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('article', models.CharField(help_text='German article (der/die/das)', max_length=3)),
                ('plural_german', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['german'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BodyPart',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('german', models.CharField(max_length=100, unique=True)),
                ('english', models.CharField(max_length=100)),
                ('french', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('article', models.CharField(help_text='German article (der/die/das)', max_length=3)),
                ('plural_german', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['german'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('german', models.CharField(max_length=100, unique=True)),
                ('english', models.CharField(max_length=100)),
                ('french', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('hex_code', models.CharField(blank=True, help_text='e.g., #FF0000', max_length=7, null=True)),
            ],
            options={
                'ordering': ['german'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('german', models.CharField(max_length=100, unique=True)),
                ('english', models.CharField(max_length=100)),
                ('french', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('article', models.CharField(help_text='German article (der/die/das)', max_length=3)),
                ('capital', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'countries',
            },
        ),
        migrations.CreateModel(
            name='FoodItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('german', models.CharField(max_length=100, unique=True)),
                ('english', models.CharField(max_length=100)),
                ('french', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('article', models.CharField(help_text='German article (der/die/das)', max_length=3)),
                ('category', models.CharField(choices=[('FRUIT', 'Fruit'), ('VEGETABLE', 'Vegetable'), ('MEAT', 'Meat'), ('DAIRY', 'Dairy'), ('GRAIN', 'Grain'), ('OTHER', 'Other')], max_length=50)),
            ],
            options={
                'ordering': ['german'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Profession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('german', models.CharField(max_length=100, unique=True)),
                ('english', models.CharField(max_length=100)),
                ('french', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('article', models.CharField(help_text='German article (der/die/das)', max_length=3)),
                ('feminine_form_german', models.CharField(blank=True, max_length=100, null=True)),
                ('feminine_form_french', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'ordering': ['german'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WeatherTerm',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('german', models.CharField(max_length=100, unique=True)),
                ('english', models.CharField(max_length=100)),
                ('french', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('category', models.CharField(choices=[('CONDITION', 'Weather Condition'), ('TEMPERATURE', 'Temperature'), ('PRECIPITATION', 'Precipitation'), ('WIND', 'Wind'), ('OTHER', 'Other')], max_length=50)),
            ],
            options={
                'ordering': ['german'],
                'abstract': False,
            },
        ),
    ]
